# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ChangePenSizeWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChangeSizeWidget(object):
    def setupUi(self, ChangeSizeWidget):
        ChangeSizeWidget.setObjectName("ChangeSizeWidget")
        ChangeSizeWidget.resize(150, 200)
        ChangeSizeWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.PenSizeScroll = QtWidgets.QScrollBar(ChangeSizeWidget)
        self.PenSizeScroll.setGeometry(QtCore.QRect(30, 10, 20, 180))
        self.PenSizeScroll.setStyleSheet("background-color: rgb(226, 226, 226);")
        self.PenSizeScroll.setMaximum(50)
        self.PenSizeScroll.setPageStep(1)
        self.PenSizeScroll.setProperty("value", 2)
        self.PenSizeScroll.setOrientation(QtCore.Qt.Vertical)
        self.PenSizeScroll.setObjectName("PenSizeScroll")
        self.PenSizeLabel = QtWidgets.QLabel(ChangeSizeWidget)
        self.PenSizeLabel.setGeometry(QtCore.QRect(80, 90, 50, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.PenSizeLabel.setFont(font)
        self.PenSizeLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.PenSizeLabel.setAutoFillBackground(False)
        self.PenSizeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.PenSizeLabel.setObjectName("PenSizeLabel")
        self.TextLabel = QtWidgets.QLabel(ChangeSizeWidget)
        self.TextLabel.setGeometry(QtCore.QRect(80, 60, 50, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.TextLabel.setFont(font)
        self.TextLabel.setAutoFillBackground(False)
        self.TextLabel.setStyleSheet("")
        self.TextLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.TextLabel.setObjectName("TextLabel")

        self.retranslateUi(ChangeSizeWidget)
        QtCore.QMetaObject.connectSlotsByName(ChangeSizeWidget)

    def retranslateUi(self, ChangeSizeWidget):
        _translate = QtCore.QCoreApplication.translate
        ChangeSizeWidget.setWindowTitle(_translate("ChangeSizeWidget", "Form"))
        self.PenSizeLabel.setText(_translate("ChangeSizeWidget", "4"))
        self.TextLabel.setText(_translate("ChangeSizeWidget", "Size:"))
